INSERT INTO public.WK01_WORKSHOP (WK01_NOME_WORKSHOP) VALUES ('JAVA 8');
INSERT INTO public.WK01_WORKSHOP (WK01_NOME_WORKSHOP) VALUES ('REACT');

ALTER SEQUENCE public.WK01_WORKSHOP_SEQ RESTART WITH 3;

